# Generated by Django 2.2.4 on 2021-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210129_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='empNUmber',
            field=models.IntegerField(),
        ),
    ]
