# Generated by Django 2.2.4 on 2021-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210129_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='empNUmber',
            field=models.CharField(max_length=10),
        ),
    ]
