# Generated by Django 2.2.4 on 2021-02-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210202_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='empNUmber',
            new_name='empNumber',
        ),
    ]
