# Generated by Django 2.2.4 on 2021-02-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210209_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='empRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.EmployeeDesignation'),
        ),
    ]
